import Head from "next/head";
import Image from "next/image";
import Logo from "../components/Logo";
import Navigator from "../components/Navigator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrap">
        <Logo />
        <Navigator />

        <div class="title-wrapeer">
          <div class="profile-image">
            <img src="images/Ellipse-1.png" />
          </div>
          <div class="text-area">
            <div class="title">제목은 여기 들어가 있습니다</div>
            <div class="info">
              <div class="author">by amdin</div>
              <div class="date">2021.12.25</div>
            </div>
          </div>
        </div>

        <div class="image-area">
          <img src="images/iiii.png" />
        </div>
        <div class="article">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam
          consequuntur excepturi libero minima placeat quasi, reiciendis.
          Aperiam atque culpa, expedita fugiat, inventore ipsum libero
          necessitatibus odio pariatur provident totam vel. Lorem ipsum dolor
          sit amet, consectetur adipisicing elit. Aliquam consequuntur excepturi
          libero minima placeat quasi, reiciendis. Aperiam atque culpa, expedita
          fugiat, inventore ipsum libero necessitatibus odio pariatur provident
          totam vel.
        </div>
      </div>
    </div>
  );
}
