import Head from "next/head";
import Image from "next/image";
import Navigator from "../components/Navigator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrapper">
        <div class="logo"></div>
        <Navigator />

        <div class="listWrapper">
          <div class="author"></div>
          <div class="createDate"></div>
          <div class="postImage">
            <img src="images/Rectangle-16.png" />
          </div>
          <div class="title">제목은 여기 들어가 있습니다.</div>
          <div class="content">
            이것은 훅텍스트 입니다. 요약을 해주는 글 입니다. 여기에 내용이 다
            들어가면 예쁘지 않아서 그냥 훅텍스트로만 사용합니다.
          </div>
          <button class="readmore">더보기 ...</button>
        </div>
      </div>
    </div>
  );
}
