import Head from "next/head";
import Image from "next/image";
import ListWrapper from "../components/ListWrapper";
import Logo from "../components/Logo";
import Navigator from "../components/Navigator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrapper">
        <Logo />
        <Navigator />
        <ListWrapper
          title="글 1 입니다."
          content="1"
          date="2022.11.11"
          author="김김김"
          imageUrl="images/Rectangle-16.png"
        />
        <ListWrapper
          title="글 2 입니다."
          content="2"
          date="2023.11.12"
          author="박박박"
          imageUrl="images/Rectangle-17.png"
        />
      </div>
    </div>
  );
}
