import Head from "next/head";
import Image from "next/image";
import Guest from "../components/Guest";
import Logo from "../components/Logo";
import Navigator from "../components/Navigator";
import Recent from "../components/Recent";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo />
      <div class="wrap">
        <Navigator />
        <div class="main-image">
          <img src="/images/main-image.png" />
        </div>

        <Recent />
        <Guest />
      </div>
    </div>
  );
}
