import Head from "next/head";
import Image from "next/image";
import Logo from "../components/Logo";
import Navigator from "../components/Navigator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrap">
        <Logo />
        <Navigator />

        <div class="bg">
          <table>
            {/* <tr>
              <td class="table-title">asdasd</td>
              <td class="table-author">22222</td>
              <td class="table-date">333333</td>
            </tr>
            <tr>
              <td>44444</td>
              <td>5555</td>
              <td>5555</td>
            </tr>
            <tr>
              <td>6666</td>
              <td>7777</td>
              <td>8888</td>
            </tr> */}
          </table>
        </div>
      </div>
    </div>
  );
}
